import { Link as RouterLink } from 'react-router-dom';
import { Box, Typography, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, Chip, Divider, Link } from '@mui/material';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import GavelIcon from '@mui/icons-material/Gavel';
import { FEEDBACK_EMAIL } from '../lib/feedback';

const AUTHOR = 'VinayakSV';
const REPO_URL = 'https://github.com/VinayakSV/ArchNorth';
const LAST_REVIEWED = 'October 4, 2026';
// Generated by every build (scripts/third-party-notices.js): exact versions and full license texts.
const NOTICES_URL = `${import.meta.env.BASE_URL}third-party-licenses.txt`;

const external = { target: '_blank', rel: 'noopener noreferrer' };
const email = <Link href={`mailto:${FEEDBACK_EMAIL}`}>{FEEDBACK_EMAIL}</Link>;

// The main libraries the site ships. Exact versions and every transitive package are in NOTICES_URL.
const LIBRARIES = [
  { name: 'React, React DOM, React Router', use: 'App framework and page navigation', license: 'MIT', url: 'https://react.dev' },
  { name: 'MUI and Emotion', use: 'Layout, components, icons, and styling', license: 'MIT', url: 'https://mui.com' },
  { name: 'React Markdown, remark-gfm, rehype-raw', use: 'Rendering the tutorials', license: 'MIT', url: 'https://github.com/remarkjs/react-markdown' },
  { name: 'React Syntax Highlighter (Prism)', use: 'Code highlighting', license: 'MIT', url: 'https://github.com/react-syntax-highlighter/react-syntax-highlighter' },
  { name: 'Mermaid', use: 'Diagrams', license: 'MIT', url: 'https://mermaid.js.org' },
  { name: 'sql.js (with SQLite)', use: 'The in-browser SQL playground. SQLite itself is public domain.', license: 'MIT', url: 'https://github.com/sql-js/sql.js' },
  { name: 'Workbox', use: 'Offline support (service worker)', license: 'MIT', url: 'https://github.com/GoogleChrome/workbox' },
  { name: 'Firebase JS SDK', use: "Sign-in for the owner's private page only", license: 'Apache-2.0', url: 'https://github.com/firebase/firebase-js-sdk' },
  { name: 'Inter and Fira Code fonts', use: 'Text and code fonts, bundled with the site', license: 'OFL-1.1', url: 'https://fontsource.org' },
];

const PROJECT_LICENSES = [
  {
    covers: 'Source code',
    name: 'MIT License',
    summary: 'Use, change, and share it freely, keeping the copyright notice.',
    url: `${REPO_URL}/blob/master/LICENSE`,
  },
  {
    covers: 'Tutorial text and diagrams',
    name: 'CC BY-NC-SA 4.0',
    summary: 'Share and adapt them with credit, for non-commercial use, under the same license.',
    url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    covers: 'Code examples in the tutorials',
    name: 'MIT-0',
    summary: 'Copy and use them anywhere, even at work, with no credit needed.',
    url: `${REPO_URL}/blob/master/LICENSE-CODE-EXAMPLES`,
  },
];

const TERMS = [
  <><strong>Free and non-commercial.</strong> No ads, no paid features, and no account.</>,
  <>The tutorials were written with AI assistance and reviewed by the author. They can still contain mistakes or go out of date, so check the official documentation before relying on them, and please <Link component={RouterLink} to="/feedback">report errors</Link>.</>,
  <><strong>Code examples are free to reuse</strong> (MIT-0), even at work. They&apos;re written for teaching, so review, test, and secure them before using them in a real system.</>,
  <>The content is general education and interview preparation, not professional advice. Everything is provided <strong>“as is”</strong>, without warranty of any kind (see the licenses above).</>,
  <>Links to other websites are provided for convenience. Those sites have their own terms and privacy policies, and ArchNorth doesn&apos;t control them.</>,
  <>ArchNorth may change, move, or go offline at any time.</>,
];

const LEGAL_NOTES = [
  <><strong>Trademarks:</strong> product and company names (for example Java, Spring, Docker, Kubernetes, AWS, Kafka, Redis, Datadog, SonarQube, Coverity, Netflix, Uber, and WhatsApp) appear only to describe technologies and well-known systems for educational purposes. All trademarks belong to their owners. ArchNorth is <strong>not affiliated with or endorsed by</strong> any of them.</>,
  <>Case studies about real companies are simplified illustrations based on public information. They are not official or insider descriptions of how those companies work.</>,
  <><strong>ShopNorth is fictional.</strong> So are the other example companies, and the people, bookings, and other sample data in the tutorials and the SQL playground. Any resemblance to real companies or people is coincidental.</>,
  <>The interview questions are original practice questions written for learning. They are not taken from any company&apos;s actual interviews.</>,
  <>The “ArchNorth” name and logo are <strong>not covered</strong> by any of these licenses.</>,
  <>Every bundled package uses a <strong>permissive license</strong> (MIT, Apache-2.0, ISC, BSD, or OFL for the fonts). The build stops if a package with a copyleft (GPL, LGPL, AGPL) or unknown license appears. DOMPurify, used by Mermaid, is dual-licensed MPL-2.0 or Apache-2.0 and is used under Apache-2.0.</>,
  <>If you believe something here infringes your copyright or other rights, email {email} with the details. It will be reviewed promptly, and corrected or removed.</>,
];

const PRIVACY = [
  <><strong>No account needed.</strong> Your notes and your light or dark theme choice are saved only in your own browser (local storage). They are never sent to a server, and clearing this site&apos;s data in your browser deletes them.</>,
  <><strong>Offline support:</strong> a service worker keeps the site&apos;s files in your browser&apos;s cache, so pages load quickly and work offline. It stores no personal data.</>,
  <><strong>Fonts</strong> are bundled with the site, so loading a page doesn&apos;t contact Google Fonts or any other font service.</>,
  <><strong>Analytics:</strong> Google Analytics 4 runs in consent mode with all storage denied, so it sets no analytics or advertising cookies. Google still receives anonymous page-view pings, including your IP address and browser details, to count visits. <Link href="https://policies.google.com/privacy" {...external}>Google&apos;s privacy policy</Link> applies to that data.</>,
  <><strong>Hosting:</strong> GitHub Pages serves the site, and GitHub logs visitors&apos; IP addresses for security. <Link href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" {...external}>GitHub&apos;s privacy statement</Link> applies.</>,
  <><strong>Sign-in</strong> (Google, through Firebase) exists only for the site owner&apos;s private page. Firebase loads only on that page, so it never runs for other visitors.</>,
  <><strong>Feedback</strong> is sent by email. Your address and message are seen only by the site owner, used only to reply and improve ArchNorth, and never shared.</>,
  <>ArchNorth is meant for adult learners and isn&apos;t directed at children.</>,
  <>Questions, or a request to delete feedback you sent: email {email}.</>,
];

const sectionTitle = (title) => (
  <>
    <Divider sx={{ my: 3 }} />
    <Typography variant="h6" fontWeight={600} sx={{ mb: 1.5 }}>{title}</Typography>
  </>
);

const bulletList = (items) => (
  <Box component="ul" sx={{ pl: 2.5, m: 0, '& li': { mb: 0.75 }, '& li::marker': { color: 'text.secondary' } }}>
    {items.map((item, i) => <li key={i}><Typography variant="body2">{item}</Typography></li>)}
  </Box>
);

export default function LicenseReport() {
  return (
    <Box sx={{ maxWidth: 900, mx: 'auto', py: 4, px: 2 }}>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 1 }}>
        <GavelIcon color="primary" fontSize="large" />
        <Typography variant="h4" fontWeight={700}>License, Credits & Privacy</Typography>
      </Box>
      <Typography variant="body2" color="text.secondary">
        Last reviewed {LAST_REVIEWED}.
      </Typography>

      {sectionTitle('Built by')}
      <Paper variant="outlined" sx={{ p: 2 }}>
        <Typography variant="body2">
          ArchNorth was designed, curated, and directed by{' '}
          <Link href="https://github.com/VinayakSV" {...external}><strong>{AUTHOR}</strong></Link>,
          and built with AI assistance. Source code:{' '}
          <Link href={REPO_URL} {...external}>{REPO_URL.replace('https://', '')}</Link>.
        </Typography>
      </Paper>

      {sectionTitle('Project Licensing')}
      <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
        {PROJECT_LICENSES.map((lic) => (
          <Paper key={lic.name} variant="outlined" sx={{ p: 2, flex: 1, minWidth: 250 }}>
            <Typography variant="subtitle2" color="text.secondary">{lic.covers}</Typography>
            <Typography variant="h6" fontWeight={600}>{lic.name}</Typography>
            <Typography variant="body2" color="text.secondary">
              {lic.summary}{' '}
              <Link href={lic.url} {...external}>Read the license</Link>
            </Typography>
          </Paper>
        ))}
      </Box>
      <Typography variant="body2" color="text.secondary" sx={{ mt: 1.5 }}>
        To credit the tutorial text, write: “Content from ArchNorth by {AUTHOR}, licensed under CC BY-NC-SA 4.0”, with a link to the source code. Code examples need no credit.
      </Typography>

      {sectionTitle('Third-Party Libraries')}
      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 1.5, gap: 1, flexWrap: 'wrap' }}>
        <Typography variant="body2" color="text.secondary">The main open-source projects ArchNorth ships:</Typography>
        <Chip icon={<CheckCircleIcon />} label="All permissive, checked on every build" color="success" size="small" />
      </Box>
      <TableContainer component={Paper} variant="outlined">
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell sx={{ fontWeight: 600 }}>Library</TableCell>
              <TableCell sx={{ fontWeight: 600 }}>Used for</TableCell>
              <TableCell sx={{ fontWeight: 600 }}>License</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {LIBRARIES.map((lib) => (
              <TableRow key={lib.name} sx={{ '&:last-child td': { border: 0 } }}>
                <TableCell><Link href={lib.url} {...external} color="inherit" underline="hover">{lib.name}</Link></TableCell>
                <TableCell sx={{ color: 'text.secondary' }}>{lib.use}</TableCell>
                <TableCell><Chip label={lib.license} size="small" variant="outlined" /></TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
      <Typography variant="body2" sx={{ mt: 1.5 }}>
        Every bundled package, with its exact version, copyright notice, and full license text:{' '}
        <Link href={NOTICES_URL} {...external}>third-party-licenses.txt</Link>
      </Typography>

      {sectionTitle('Using ArchNorth')}
      {bulletList(TERMS)}

      {sectionTitle('Legal Notes')}
      {bulletList(LEGAL_NOTES)}

      {sectionTitle('Privacy')}
      {bulletList(PRIVACY)}

      <Paper variant="outlined" sx={{ p: 2, mt: 4, bgcolor: 'action.hover' }}>
        <Typography variant="body2" color="text.secondary" textAlign="center">
          Copyright © 2026 {AUTHOR} — Code: MIT | Content: CC BY-NC-SA 4.0 | Code examples: MIT-0
        </Typography>
      </Paper>
    </Box>
  );
}
