import {
  Architecture, Speed, Dns, CloudQueue, AccountBalance, Memory,
  Code, DataObject, Hub, Layers, Cached, Settings, Sync,
  AccountTree, Storage, Api, Security, Bolt, Category, Stream,
  CloudUpload, LiveTv, CompareArrows, Shield, Cloud, SmartToy,
  Gavel, Waves, Language, Balance, LocalTaxi, Atm, TravelExplore,
  TrafficOutlined, SportsEsports, OndemandVideo, Search, CloudSync,
  Timer, Recommend, LocalParking, DynamicFeed, Forum, Link, Chat,
  Elevator, Casino, ConfirmationNumber, Receipt, LocalLibrary,
  PointOfSale, Extension, TableChart, Psychology, ViewInAr, AutoAwesome,
  Anchor, Lan, RocketLaunch, Route, VerifiedUser, Tune, FindInPage, EnergySavingsLeaf,
  Storefront, Assignment, BugReport, FactCheck, MonitorHeart, Celebration,
  TrendingUp, HealthAndSafety, ChangeHistory, CopyAll, HowToVote,
  VpnKey, Router, Computer, Functions, Inbox, CallSplit, Inventory2, Public,
  IntegrationInstructions, Insights,
} from '@mui/icons-material';

const tutorialRegistry = [
  // ── ShopNorth Journey (the main story: one e-commerce product through the whole SDLC) ──
  {
    id: 'journey-start',
    title: 'Start Here — The ShopNorth Story',
    description: 'Meet ShopNorth, a fictional online store, and the team that will take it from idea to production — the map for the whole journey',
    category: 'ShopNorth Journey',
    subcategory: 'Start Here',
    icon: Storefront,
    tags: ['SDLC', 'E-commerce', 'Story', 'Roadmap'],
  },
  {
    id: 'journey-01-requirements',
    title: 'Ch 1 · Requirements & Planning',
    description: 'Turn a business idea into user stories, acceptance criteria, non-functional requirements with numbers, and a 12-week plan',
    category: 'ShopNorth Journey',
    subcategory: 'Plan & Design',
    icon: Assignment,
    tags: ['Requirements', 'User Stories', 'NFRs', 'Estimation', 'Agile'],
  },
  {
    id: 'journey-02-system-design',
    title: 'Ch 2 · System Design (HLD)',
    description: 'Design ShopNorth end to end — services, data stores, caching, search, payments, and the decisions behind them',
    category: 'ShopNorth Journey',
    subcategory: 'Plan & Design',
    icon: Architecture,
    tags: ['HLD', 'Architecture', 'ADRs', 'Capacity Planning'],
  },
  {
    id: 'journey-03-low-level-design',
    title: 'Ch 3 · Low-Level Design',
    description: 'Model orders, carts, pricing, and inventory reservations as clean Java classes with the right patterns',
    category: 'ShopNorth Journey',
    subcategory: 'Plan & Design',
    icon: Extension,
    tags: ['LLD', 'State Machine', 'Strategy Pattern', 'Value Objects'],
  },
  {
    id: 'journey-04-data-sql',
    title: 'Ch 4 · Data Model & SQL',
    description: 'Design the PostgreSQL schema, constraints, indexes, migrations, and the queries the business actually runs',
    category: 'ShopNorth Journey',
    subcategory: 'Plan & Design',
    icon: Storage,
    tags: ['PostgreSQL', 'Schema Design', 'Indexes', 'Flyway', 'Reporting'],
  },
  {
    id: 'journey-05-spring-boot',
    title: 'Ch 5 · Building with Spring Boot',
    description: 'Build the order service — REST API, validation, transactions, idempotency, resilient remote calls, and error handling',
    category: 'ShopNorth Journey',
    subcategory: 'Build',
    icon: EnergySavingsLeaf,
    tags: ['Spring Boot', 'REST', '@Transactional', 'Idempotency', 'Resilience4j'],
  },
  {
    id: 'journey-06-microservices',
    title: 'Ch 6 · Microservices & Events',
    description: 'Split ShopNorth into a few well-bounded services, connect them with Kafka, and run checkout as a saga with the outbox pattern',
    category: 'ShopNorth Journey',
    subcategory: 'Build',
    icon: Hub,
    tags: ['Microservices', 'Kafka', 'Saga', 'Outbox', 'API Gateway'],
  },
  {
    id: 'journey-07-security',
    title: 'Ch 7 · Security & Login',
    description: 'Customer and admin login with Auth0, API authorization, payment webhooks, secrets, and the OWASP risks that matter for a store',
    category: 'ShopNorth Journey',
    subcategory: 'Build',
    icon: Security,
    tags: ['Auth0', 'JWT', 'OWASP', 'PCI DSS', 'Secrets'],
  },
  {
    id: 'journey-08-testing',
    title: 'Ch 8 · Testing — Unit to Regression',
    description: 'The full test strategy: unit, integration with Testcontainers, contract, end-to-end, smoke, regression, and load tests',
    category: 'ShopNorth Journey',
    subcategory: 'Quality',
    icon: BugReport,
    tags: ['JUnit 5', 'Testcontainers', 'Smoke Test', 'Regression', 'k6'],
  },
  {
    id: 'journey-09-code-quality',
    title: 'Ch 9 · Code Quality — SonarQube & Coverity',
    description: 'Code review, quality gates, static analysis, dependency and secret scanning — catching defects before they ship',
    category: 'ShopNorth Journey',
    subcategory: 'Quality',
    icon: FactCheck,
    tags: ['SonarQube', 'Coverity', 'JaCoCo', 'SAST', 'Code Review'],
  },
  {
    id: 'journey-10-docker',
    title: 'Ch 10 · Containerizing with Docker',
    description: 'Package the order service as a secure image and run the whole ShopNorth stack locally with Docker Compose',
    category: 'ShopNorth Journey',
    subcategory: 'Ship',
    icon: ViewInAr,
    tags: ['Docker', 'Docker Compose', 'Trivy', 'Local Dev'],
  },
  {
    id: 'journey-11-cicd',
    title: 'Ch 11 · CI/CD Pipeline',
    description: 'From pull request to production: build, test, scan, image, staging, smoke and regression tests, approval, canary release',
    category: 'ShopNorth Journey',
    subcategory: 'Ship',
    icon: Sync,
    tags: ['GitHub Actions', 'GitOps', 'Argo CD', 'Canary', 'DORA'],
  },
  {
    id: 'journey-12-kubernetes',
    title: 'Ch 12 · Deploying on Kubernetes',
    description: 'Run ShopNorth on Kubernetes — deployments, probes, config and secrets, autoscaling, ingress, and safe rollouts',
    category: 'ShopNorth Journey',
    subcategory: 'Ship',
    icon: Anchor,
    tags: ['Kubernetes', 'Helm', 'HPA', 'Ingress', 'Argo Rollouts'],
  },
  {
    id: 'journey-13-observability',
    title: 'Ch 13 · Observability with Datadog',
    description: 'Logs, metrics, traces, dashboards, monitors, SLOs, and synthetic tests — knowing ShopNorth is healthy before customers tell you',
    category: 'ShopNorth Journey',
    subcategory: 'Operate & Evolve',
    icon: MonitorHeart,
    tags: ['Datadog', 'APM', 'SLOs', 'Monitors', 'Synthetics'],
  },
  {
    id: 'journey-14-launch-day',
    title: 'Ch 14 · Launch Day & Incidents',
    description: 'Prepare for the Diwali sale, survive the 8 PM spike, handle a payment incident, and write the postmortem',
    category: 'ShopNorth Journey',
    subcategory: 'Operate & Evolve',
    icon: Celebration,
    tags: ['Load Testing', 'Incident Response', 'Postmortem', 'Feature Flags'],
  },
  {
    id: 'journey-15-ai',
    title: 'Ch 15 · Evolving with AI',
    description: 'Add AI search and a support assistant the safe way, use AI across the SDLC, and wrap up the whole journey',
    category: 'ShopNorth Journey',
    subcategory: 'Operate & Evolve',
    icon: AutoAwesome,
    tags: ['RAG', 'AI Search', 'Support Assistant', 'AI-SDLC'],
  },
  // ── System Design ──
  {
    id: 'thinking-system-design',
    title: 'How to Think in System Design',
    description: 'The mental framework — how to approach ANY system design problem from scratch, step by step',
    category: 'System Design',
    subcategory: 'Foundation',
    icon: Architecture,
    tags: ['HLD', 'Framework', 'Thinking', 'Estimation', 'Trade-offs'],
  },
  {
    id: 'scalability',
    title: 'Scalability — Vertical, Horizontal & the Bottleneck',
    description: "Little's law, stateless services, the read ladder, write scaling, back-pressure, and capacity planning for ShopNorth's 10x sale",
    category: 'System Design',
    subcategory: 'Core Concepts',
    icon: TrendingUp,
    tags: ['Scalability', 'Horizontal Scaling', 'Caching', 'Capacity Planning', "Little's Law"],
  },
  {
    id: 'high-availability',
    title: 'High Availability & Disaster Recovery',
    description: 'Availability math, removing single points of failure, failover, timeouts and retries with jitter, multi-AZ vs multi-region, RPO and RTO',
    category: 'System Design',
    subcategory: 'Core Concepts',
    icon: HealthAndSafety,
    tags: ['High Availability', 'Disaster Recovery', 'RPO', 'RTO', 'Failover', 'Resilience'],
  },
  {
    id: 'cap-theorem',
    title: 'CAP Theorem, PACELC & Consistency Models',
    description: 'What CAP really says, CP vs AP, PACELC, the consistency ladder, and choosing consistency per operation: strong for stock and money, eventual for browsing',
    category: 'System Design',
    subcategory: 'Core Concepts',
    icon: ChangeHistory,
    tags: ['CAP', 'PACELC', 'Consistency', 'Eventual Consistency', 'Linearizability'],
  },
  {
    id: 'replication-partitioning',
    title: 'Replication & Sharding',
    description: 'Leader-follower and quorum replication, replication lag, Multi-AZ vs read replicas, partitioning strategies, consistent hashing, hot keys, resharding',
    category: 'System Design',
    subcategory: 'Core Concepts',
    icon: CopyAll,
    tags: ['Replication', 'Sharding', 'Partitioning', 'Consistent Hashing', 'Quorum'],
  },
  {
    id: 'consensus-coordination',
    title: 'Consensus, Leader Election & Distributed Locks',
    description: 'Raft in five minutes, quorums, SKIP LOCKED vs leases vs database invariants, ShedLock, fencing tokens, clocks, and split brain',
    category: 'System Design',
    subcategory: 'Core Concepts',
    icon: HowToVote,
    tags: ['Consensus', 'Raft', 'Leader Election', 'Distributed Locks', 'Fencing Tokens'],
  },
  {
    id: 'load-balancing',
    title: 'Load Balancing — The Complete Guide',
    description: 'L4 vs L7, algorithms, health checks, sticky sessions, ALB vs NLB vs HAProxy — when to use what',
    category: 'System Design',
    subcategory: 'Building Blocks',
    icon: Balance,
    tags: ['Load Balancer', 'ALB', 'NLB', 'HAProxy', 'L4', 'L7', 'HLD'],
  },
  {
    id: 'cdn-deep-dive',
    title: 'CDN — Content Delivery Networks',
    description: 'How CDNs work — edge caching, origin shield, cache invalidation, CloudFront vs Akamai vs Cloudflare',
    category: 'System Design',
    subcategory: 'Building Blocks',
    icon: Language,
    tags: ['CDN', 'Edge Caching', 'CloudFront', 'Cache Invalidation', 'HLD'],
  },
  {
    id: 'cache-system',
    title: 'Distributed Cache',
    description: 'Design a distributed caching system — eviction, consistency, replication',
    category: 'System Design',
    subcategory: 'Building Blocks',
    icon: Cached,
    tags: ['HLD', 'LLD', 'LRU', 'Consistent Hashing', 'Redis'],
  },
  {
    id: 'rate-limiter',
    title: 'Rate Limiter',
    description: 'Design a distributed rate limiter to protect APIs from abuse',
    category: 'System Design',
    subcategory: 'Building Blocks',
    icon: Speed,
    tags: ['HLD', 'LLD', 'Token Bucket', 'Sliding Window'],
  },
  {
    id: 'design-rate-limiter-distributed',
    title: 'Design Distributed Rate Limiter',
    description: 'API rate limiting at scale — token bucket, sliding window, Redis-based, distributed coordination',
    category: 'System Design',
    subcategory: 'Building Blocks',
    icon: Timer,
    tags: ['HLD', 'Rate Limiting', 'Redis', 'Distributed', 'Token Bucket'],
  },
  {
    id: 'url-shortener',
    title: 'URL Shortener',
    description: 'Design a scalable URL shortening service like TinyURL / Bitly',
    category: 'System Design',
    subcategory: 'Classic Designs',
    icon: Dns,
    tags: ['HLD', 'LLD', 'Hashing', 'Database'],
  },
  {
    id: 'design-url-shortener',
    title: 'Design URL Shortener (Interview Edition)',
    description: 'Complete interview walkthrough — hashing, base62, collision handling, analytics, custom URLs',
    category: 'System Design',
    subcategory: 'Classic Designs',
    icon: Link,
    tags: ['HLD', 'LLD', 'Hashing', 'Base62', 'Analytics'],
  },
  {
    id: 'notification-system',
    title: 'Notification System',
    description: 'Design a multi-channel notification system — push, email, SMS at scale',
    category: 'System Design',
    subcategory: 'Classic Designs',
    icon: CloudQueue,
    tags: ['HLD', 'Message Queue', 'Fan-out', 'Priority'],
  },
  {
    id: 'design-typeahead',
    title: 'Design Typeahead / Autocomplete',
    description: 'Search autocomplete — trie data structure, ranking, real-time suggestions, personalization',
    category: 'System Design',
    subcategory: 'Classic Designs',
    icon: Search,
    tags: ['HLD', 'Trie', 'Ranking', 'Real-Time', 'NLP'],
  },
  {
    id: 'design-web-crawler',
    title: 'Design Web Crawler',
    description: 'Scalable web crawler — URL frontier, politeness, deduplication, distributed crawling',
    category: 'System Design',
    subcategory: 'Classic Designs',
    icon: TravelExplore,
    tags: ['HLD', 'Crawling', 'URL Frontier', 'Distributed'],
  },
  {
    id: 'design-cloud-storage',
    title: 'Design Google Drive / Dropbox',
    description: 'Cloud file storage — chunking, sync, conflict resolution, deduplication, sharing',
    category: 'System Design',
    subcategory: 'Classic Designs',
    icon: CloudSync,
    tags: ['HLD', 'File Sync', 'Chunking', 'Conflict Resolution'],
  },
  {
    id: 'design-ride-sharing',
    title: 'Design Uber / Ola / Lyft',
    description: 'Ride-sharing system — real-time matching, geospatial indexing, ETA calculation, dispatch system',
    category: 'System Design',
    subcategory: 'Classic Designs',
    icon: LocalTaxi,
    tags: ['HLD', 'LLD', 'Geospatial', 'Real-Time', 'Matching'],
  },
  {
    id: 'design-newsfeed',
    title: 'Design Facebook Newsfeed',
    description: 'Social media feed — fanout, ranking, real-time updates, sharding, celebrity problem',
    category: 'System Design',
    subcategory: 'Social & Media',
    icon: DynamicFeed,
    tags: ['HLD', 'Fanout', 'Ranking', 'Sharding', 'Real-Time'],
  },
  {
    id: 'design-chat-system',
    title: 'Design WhatsApp / Messenger',
    description: 'Chat system — WebSocket, message delivery, encryption, group chat, presence, offline handling',
    category: 'System Design',
    subcategory: 'Social & Media',
    icon: Chat,
    tags: ['HLD', 'WebSocket', 'Encryption', 'Presence', 'Group Chat'],
  },
  {
    id: 'design-forum',
    title: 'Design Reddit / Quora / HackerNews',
    description: 'Forum system — posts, comments, voting, tags, newsfeed, search, moderation',
    category: 'System Design',
    subcategory: 'Social & Media',
    icon: Forum,
    tags: ['HLD', 'Voting', 'Tags', 'Search', 'Moderation'],
  },
  {
    id: 'design-netflix',
    title: 'Design Netflix',
    description: 'Video streaming platform — transcoding, adaptive bitrate, CDN, recommendation engine',
    category: 'System Design',
    subcategory: 'Social & Media',
    icon: OndemandVideo,
    tags: ['HLD', 'Streaming', 'CDN', 'Recommendation', 'Transcoding'],
  },
  {
    id: 'design-recommendation',
    title: 'Design Recommendation System',
    description: 'Recommendation engine — collaborative filtering, content-based, hybrid, real-time personalization',
    category: 'System Design',
    subcategory: 'Social & Media',
    icon: Recommend,
    tags: ['HLD', 'ML', 'Collaborative Filtering', 'Personalization'],
  },
  {
    id: 'payment-gateway',
    title: 'Payment Gateway',
    description: 'Design a payment processing system — idempotency, retries, reconciliation',
    category: 'System Design',
    subcategory: 'Financial Domain',
    icon: AccountBalance,
    tags: ['HLD', 'LLD', 'Idempotency', 'Transactions', 'Finance'],
  },
  {
    id: 'stock-trading-platform',
    title: 'Stock Trading Platform',
    description: 'Design a real-time stock trading system with order matching engine',
    category: 'System Design',
    subcategory: 'Financial Domain',
    icon: AccountBalance,
    tags: ['HLD', 'Order Matching', 'Event Sourcing', 'Finance'],
  },
  {
    id: 'fraud-detection-system',
    title: 'Fraud Detection System',
    description: 'Design a real-time fraud detection pipeline for financial transactions',
    category: 'System Design',
    subcategory: 'Financial Domain',
    icon: Security,
    tags: ['HLD', 'Stream Processing', 'ML Pipeline', 'Finance'],
  },
  // ── Low-Level Design ──
  {
    id: 'lld-thinking-framework',
    title: 'How to Think in LLD',
    description: 'The mental framework — how to break ANY problem into classes, patterns, and relationships from scratch',
    category: 'Low-Level Design',
    subcategory: 'Foundation',
    icon: Extension,
    tags: ['LLD', 'OOP', 'SOLID', 'Design Patterns', 'Framework', 'Thinking'],
  },
  {
    id: 'design-parking-lot',
    title: 'Design Parking Lot System',
    description: 'Parking management — spot allocation, pricing, multi-level, vehicle types, real-time availability',
    category: 'Low-Level Design',
    subcategory: 'Booking & Business Apps',
    icon: LocalParking,
    tags: ['LLD', 'OOP', 'State Management', 'Pricing'],
  },
  {
    id: 'lld-library',
    title: 'Design Library Management System',
    description: 'OOP design — books, members, borrowing, fines, search, reservation, notifications',
    category: 'Low-Level Design',
    subcategory: 'Booking & Business Apps',
    icon: LocalLibrary,
    tags: ['LLD', 'OOP', 'CRUD', 'Observer Pattern'],
  },
  {
    id: 'lld-bookmyshow',
    title: 'Design BookMyShow / Movie Tickets',
    description: 'OOP design — seat selection, concurrent booking, payment, show management',
    category: 'Low-Level Design',
    subcategory: 'Booking & Business Apps',
    icon: ConfirmationNumber,
    tags: ['LLD', 'OOP', 'Concurrency', 'Booking System'],
  },
  {
    id: 'lld-splitwise',
    title: 'Design Splitwise / Expense Sharing',
    description: 'OOP design — expense splitting (equal, exact, percentage), debt simplification, group management',
    category: 'Low-Level Design',
    subcategory: 'Booking & Business Apps',
    icon: Receipt,
    tags: ['LLD', 'OOP', 'Strategy Pattern', 'Graph Algorithm'],
  },
  {
    id: 'lld-vending-machine',
    title: 'Design Vending Machine',
    description: 'OOP design — state pattern, coin handling, product dispensing, inventory, refund',
    category: 'Low-Level Design',
    subcategory: 'State Machines & Devices',
    icon: PointOfSale,
    tags: ['LLD', 'OOP', 'State Pattern', 'Chain of Responsibility'],
  },
  {
    id: 'lld-elevator',
    title: 'Design Elevator System',
    description: 'OOP design — scheduling algorithms, state machine, multi-elevator coordination, SOLID principles',
    category: 'Low-Level Design',
    subcategory: 'State Machines & Devices',
    icon: Elevator,
    tags: ['LLD', 'OOP', 'State Machine', 'Strategy Pattern', 'SOLID'],
  },
  {
    id: 'design-atm',
    title: 'Design ATM System',
    description: 'ATM architecture — authentication, transaction handling, timeout recovery, cash dispensing',
    category: 'Low-Level Design',
    subcategory: 'State Machines & Devices',
    icon: Atm,
    tags: ['HLD', 'LLD', 'Transactions', 'State Machine'],
  },
  {
    id: 'design-traffic-control',
    title: 'Design Traffic Control System',
    description: 'Smart traffic lights — state machines, scheduling, sensor integration, emergency override',
    category: 'Low-Level Design',
    subcategory: 'State Machines & Devices',
    icon: TrafficOutlined,
    tags: ['LLD', 'State Machine', 'Scheduling', 'IoT'],
  },
  {
    id: 'design-tic-tac-toe',
    title: 'Design Tic-Tac-Toe Game',
    description: 'Multiplayer game — game engine, AI opponent, win detection, real-time sync',
    category: 'Low-Level Design',
    subcategory: 'Games',
    icon: SportsEsports,
    tags: ['LLD', 'Game Design', 'AI', 'State Management'],
  },
  {
    id: 'lld-snake-ladder',
    title: 'Design Snake & Ladder Game',
    description: 'OOP design — board, dice, players, game engine, turn management, win detection',
    category: 'Low-Level Design',
    subcategory: 'Games',
    icon: Casino,
    tags: ['LLD', 'OOP', 'Game Design', 'State Machine'],
  },
  {
    id: 'lld-chess',
    title: 'Design Chess Game',
    description: 'OOP design — pieces, board, move validation, check/checkmate detection, game history',
    category: 'Low-Level Design',
    subcategory: 'Games',
    icon: Extension,
    tags: ['LLD', 'OOP', 'Polymorphism', 'Command Pattern'],
  },
  // ── Real-World Builds ──
  {
    id: 'data-ingestion-platform',
    title: 'Data Ingestion Platform',
    description: 'Multi-tenant CSV/file upload system — heavy data processing, parallel pipelines, tenant isolation at scale',
    category: 'Real-World Builds',
    subcategory: 'Data Engineering',
    icon: CloudUpload,
    tags: ['Multi-Tenant', 'CSV', 'Batch Processing', 'S3', 'Kafka', 'Worker Pools'],
  },
  {
    id: 'live-streaming-platform',
    title: 'Live Streaming Platform',
    description: 'HotStar/Netflix-scale live streaming — millions of concurrent viewers, CDN, adaptive bitrate, chat',
    category: 'Real-World Builds',
    subcategory: 'High-Scale Systems',
    icon: LiveTv,
    tags: ['CDN', 'HLS', 'WebSocket', 'Edge Computing', 'Millions RPS'],
  },
  // ── Architecture Decisions ──
  {
    id: 'thinking-architecture',
    title: 'How to Think in Architecture',
    description: 'The mental framework — how to evaluate trade-offs, pick technologies, and make decisions you won\'t regret',
    category: 'Architecture Decisions',
    subcategory: 'Foundation',
    icon: CompareArrows,
    tags: ['Architecture', 'Framework', 'Thinking', 'Trade-offs', 'Decision Making'],
  },
  {
    id: 'database-decisions',
    title: 'Database Decisions',
    description: 'SQL vs NoSQL, sharding strategies, indexing, schema design — when to pick what and why',
    category: 'Architecture Decisions',
    subcategory: 'Data Layer',
    icon: Storage,
    tags: ['SQL', 'NoSQL', 'Sharding', 'Indexing', 'Schema Design', 'DynamoDB', 'PostgreSQL'],
  },
  {
    id: 'caching-strategy',
    title: 'Caching Strategy',
    description: 'Redis vs Memcached vs local cache — eviction policies, invalidation patterns, cache-aside vs write-through',
    category: 'Architecture Decisions',
    subcategory: 'Data Layer',
    icon: Cached,
    tags: ['Redis', 'Memcached', 'Cache-Aside', 'Write-Through', 'TTL', 'Invalidation'],
  },
  {
    id: 'messaging-decisions',
    title: 'Messaging & Event Systems',
    description: 'Kafka vs RabbitMQ vs SQS vs SNS — delivery guarantees, ordering, throughput, when to use each',
    category: 'Architecture Decisions',
    subcategory: 'Communication',
    icon: Stream,
    tags: ['Kafka', 'RabbitMQ', 'SQS', 'SNS', 'Event-Driven', 'Pub/Sub'],
  },
  {
    id: 'auth-security-decisions',
    title: 'Auth & Security Decisions',
    description: 'OAuth2, OIDC, x509, JWT, session — SPA vs server app vs API, Auth0, Cognito, real-world flows',
    category: 'Architecture Decisions',
    subcategory: 'Security',
    icon: Shield,
    tags: ['OAuth2', 'OIDC', 'JWT', 'x509', 'Auth0', 'Cognito', 'SPA', 'mTLS'],
  },
  {
    id: 'auth0-deep-dive',
    title: 'Auth0 — Zero to Industry Implementation',
    description: 'Complete Auth0 guide — OAuth2, OIDC, JWT, Spring Boot integration, SPA flows, RBAC, multi-tenancy, Actions, and senior interview Q&A',
    category: 'Architecture Decisions',
    subcategory: 'Security',
    icon: Shield,
    tags: ['Auth0', 'OAuth2', 'OIDC', 'JWT', 'Spring Security', 'RBAC', 'Multi-Tenant', 'SSO'],
  },
  {
    id: 'cloud-infra-decisions',
    title: 'Cloud & Infrastructure',
    description: 'AWS services decision tree — ALB vs NLB, Lambda vs ECS vs EKS, RDS vs DynamoDB, Secrets Manager, VPC design',
    category: 'Architecture Decisions',
    subcategory: 'Cloud & DevOps',
    icon: Cloud,
    tags: ['AWS', 'ALB', 'NLB', 'Lambda', 'ECS', 'EKS', 'Docker', 'K8s', 'Terraform'],
  },
  // ── AI Engineering ──
  {
    id: 'ai-roadmap',
    title: 'AI Engineer Roadmap — Step by Step',
    description: 'The stage-by-stage path from full-stack developer (or anyone) to building production AI features — what to learn, in what order, and a project per stage',
    category: 'AI Engineering',
    subcategory: 'Start Here',
    icon: Route,
    tags: ['Roadmap', 'Gen AI', 'Career', 'Learning Path', 'Projects'],
  },
  {
    id: 'genai-fundamentals',
    title: 'Gen AI Fundamentals — How LLMs Work',
    description: 'Tokens, embeddings, transformers intuition, context windows, sampling, hallucinations, model choice and cost — the mental model every AI builder needs',
    category: 'AI Engineering',
    subcategory: 'Foundations',
    icon: Psychology,
    tags: ['LLM', 'Tokens', 'Embeddings', 'Transformers', 'Context Window', 'Hallucination'],
  },
  {
    id: 'prompt-engineering',
    title: 'Prompt Engineering & Structured Output',
    description: 'System prompts, few-shot examples, reasoning, JSON/structured outputs, prompt testing — prompting as an engineering discipline',
    category: 'AI Engineering',
    subcategory: 'Foundations',
    icon: Tune,
    tags: ['Prompting', 'Few-Shot', 'Structured Output', 'JSON', 'System Prompt'],
  },
  {
    id: 'llm-app-development',
    title: 'Building LLM Apps — APIs, Streaming, Tool Use',
    description: 'Calling LLM APIs from Java/Spring and JavaScript — streaming, function calling, retries, rate limits, caching, and cost control',
    category: 'AI Engineering',
    subcategory: 'Building with LLMs',
    icon: Code,
    tags: ['LLM API', 'Spring AI', 'Streaming', 'Tool Use', 'Function Calling', 'Cost'],
  },
  {
    id: 'rag-deep-dive',
    title: 'RAG — Retrieval-Augmented Generation',
    description: 'Embeddings, chunking, pgvector, hybrid search, reranking, citations, and evaluating retrieval — build a RAG service end to end',
    category: 'AI Engineering',
    subcategory: 'Building with LLMs',
    icon: FindInPage,
    tags: ['RAG', 'Embeddings', 'Vector DB', 'pgvector', 'Chunking', 'Reranking'],
  },
  {
    id: 'ai-agents',
    title: 'AI Agents — Tools, Loops, and Guardrails',
    description: 'What an agent really is, the agent loop, tool design, planning, memory, multi-agent patterns, and when NOT to build an agent',
    category: 'AI Engineering',
    subcategory: 'Agents & MCP',
    icon: SmartToy,
    tags: ['Agents', 'Tool Use', 'Agent Loop', 'Multi-Agent', 'Guardrails', 'Memory'],
  },
  {
    id: 'mcp-deep-dive',
    title: 'MCP — Model Context Protocol',
    description: 'Complete guide to MCP: the open standard connecting AI to your systems — servers, clients, tools, resources, and building real integrations from scratch',
    category: 'AI Engineering',
    subcategory: 'Agents & MCP',
    icon: Hub,
    tags: ['MCP', 'LLM', 'AI Integration', 'Claude', 'Tools', 'Resources', 'JSON-RPC', 'Agentic'],
  },
  {
    id: 'ai-production-llmops',
    title: 'AI in Production — Evals, Guardrails, LLMOps',
    description: 'Evaluation datasets, LLM-as-judge, observability, prompt injection defense, PII, cost and latency budgets — shipping AI features safely',
    category: 'AI Engineering',
    subcategory: 'Production & Process',
    icon: VerifiedUser,
    tags: ['Evals', 'LLMOps', 'Guardrails', 'Prompt Injection', 'Observability', 'Cost'],
  },
  {
    id: 'ai-in-system-design',
    title: 'AI in System Design',
    description: 'When and where to include AI/ML — RAG, embeddings, LLM integration, model serving, cost vs accuracy trade-offs',
    category: 'AI Engineering',
    subcategory: 'Production & Process',
    icon: SmartToy,
    tags: ['AI', 'RAG', 'LLM', 'Embeddings', 'Model Serving', 'Vector DB', 'Cost Trade-offs'],
  },
  {
    id: 'ai-sdlc',
    title: 'AI-SDLC — AI Across the Delivery Lifecycle',
    description: 'Using AI in every SDLC phase — maturity model, spec-driven development, context engineering, guardrails, metrics, and a 6-month adoption roadmap',
    category: 'AI Engineering',
    subcategory: 'Production & Process',
    icon: AutoAwesome,
    tags: ['AI-SDLC', 'AI Agents', 'Spec-Driven', 'Guardrails', 'DORA', 'LLMOps', 'Claude Code'],
  },
  // ── Microservices ──
  {
    id: 'thinking-microservices',
    title: 'How to Think in Microservices',
    description: 'The mental framework — when to split, how to communicate, what patterns to apply and WHY',
    category: 'Microservices',
    subcategory: 'Foundation',
    icon: Hub,
    tags: ['Microservices', 'Framework', 'Thinking', 'Monolith', 'Trade-offs'],
  },
  {
    id: 'microservices-patterns',
    title: 'Microservices Patterns',
    description: 'Saga, CQRS, Event Sourcing, Circuit Breaker — when and why to use each',
    category: 'Microservices',
    subcategory: 'Patterns & Approaches',
    icon: Hub,
    tags: ['Saga', 'CQRS', 'Event Sourcing', 'Circuit Breaker'],
  },
  {
    id: 'service-communication',
    title: 'Service Communication',
    description: 'REST vs gRPC vs messaging — sync vs async, when to pick what',
    category: 'Microservices',
    subcategory: 'Patterns & Approaches',
    icon: Api,
    tags: ['REST', 'gRPC', 'Kafka', 'RabbitMQ'],
  },
  {
    id: 'api-gateway-pattern',
    title: 'API Gateway Pattern',
    description: 'Routing, auth, rate limiting, aggregation — the front door of microservices',
    category: 'Microservices',
    subcategory: 'Patterns & Approaches',
    icon: Layers,
    tags: ['API Gateway', 'BFF', 'Routing', 'Auth'],
  },
  {
    id: 'distributed-transactions',
    title: 'Distributed Transactions',
    description: '2PC, Saga, Outbox pattern — handling transactions across services',
    category: 'Microservices',
    subcategory: 'Data Management',
    icon: Sync,
    tags: ['2PC', 'Saga', 'Outbox', 'Eventual Consistency'],
  },
  {
    id: 'kafka-deep-dive',
    title: 'Apache Kafka Deep Dive',
    description: 'Producers, consumers, partitions, offsets — hands-on with Docker setup for Windows & Mac',
    category: 'Microservices',
    subcategory: 'Messaging & Streaming',
    icon: Stream,
    tags: ['Kafka', 'Event Streaming', 'Producers', 'Consumers', 'Hands-On'],
  },
  {
    id: 'service-discovery',
    title: 'Service Discovery & Config',
    description: 'How services find each other — Eureka, Consul, K8s DNS, externalized config',
    category: 'Microservices',
    subcategory: 'Infrastructure',
    icon: Settings,
    tags: ['Eureka', 'Consul', 'Config Server', 'K8s'],
  },
  // ── Java ──
  {
    id: 'thinking-java',
    title: 'How to Think in Java',
    description: 'The mental framework — how to pick the right collection, concurrency tool, and Java feature for any problem',
    category: 'Java',
    subcategory: 'Foundation',
    icon: Code,
    tags: ['Java', 'Framework', 'Thinking', 'Collections', 'Concurrency'],
  },
  {
    id: 'java-oop',
    title: 'OOP — The Four Pillars',
    description: 'Encapsulation, inheritance, polymorphism, abstraction — with SOLID connections and interview patterns',
    category: 'Java',
    subcategory: 'Core Java',
    icon: Code,
    tags: ['OOP', 'SOLID', 'Encapsulation', 'Polymorphism', 'Abstraction'],
  },
  {
    id: 'java-equals-hashcode',
    title: 'equals(), hashCode() & Immutability',
    description: '== vs .equals(), the contract, why breaking it breaks HashMap, immutable class design',
    category: 'Java',
    subcategory: 'Core Java',
    icon: DataObject,
    tags: ['equals', 'hashCode', 'Immutability', 'String', 'Contract'],
  },
  {
    id: 'java-strings',
    title: 'Strings — Pool, Builder, Buffer',
    description: 'String immutability, string pool, intern(), StringBuilder vs StringBuffer, common interview traps',
    category: 'Java',
    subcategory: 'Core Java',
    icon: Code,
    tags: ['String', 'StringBuilder', 'StringBuffer', 'String Pool', 'Immutability'],
  },
  {
    id: 'java-exceptions',
    title: 'Exceptions — Checked, Unchecked, try-with-resources',
    description: 'Exception hierarchy, checked vs unchecked, try-with-resources, custom exceptions, Spring wrapping',
    category: 'Java',
    subcategory: 'Core Java',
    icon: Code,
    tags: ['Checked', 'Unchecked', 'try-with-resources', 'Custom Exceptions', 'AutoCloseable'],
  },
  {
    id: 'java-collections-list',
    title: 'Collections — List, Queue, Set',
    description: 'ArrayList vs LinkedList vs ArrayDeque, HashSet vs TreeSet, Comparator vs Comparable',
    category: 'Java',
    subcategory: 'Collections & Data Structures',
    icon: DataObject,
    tags: ['ArrayList', 'LinkedList', 'HashSet', 'TreeSet', 'Comparator'],
  },
  {
    id: 'hashmap-internals',
    title: 'HashMap Internals',
    description: 'How HashMap really works — hashing, buckets, tree-ification, resize with real scenarios',
    category: 'Java',
    subcategory: 'Collections & Data Structures',
    icon: DataObject,
    tags: ['HashMap', 'Hashing', 'Internals', 'Scenarios'],
  },
  {
    id: 'concurrent-hashmap',
    title: 'ConcurrentHashMap Deep Dive',
    description: 'Thread-safe maps — segment locking vs CAS, real-world usage scenarios',
    category: 'Java',
    subcategory: 'Collections & Data Structures',
    icon: DataObject,
    tags: ['ConcurrentHashMap', 'Thread Safety', 'CAS'],
  },
  {
    id: 'multithreading',
    title: 'Multithreading & Concurrency',
    description: 'Threads, executors, locks, synchronized, volatile — scenario-based with examples',
    category: 'Java',
    subcategory: 'Concurrency & Parallelism',
    icon: AccountTree,
    tags: ['Threads', 'ExecutorService', 'Locks', 'Volatile'],
  },
  {
    id: 'completable-future',
    title: 'CompletableFuture & Parallel Streams',
    description: 'Async programming in Java — chaining, combining, error handling with real examples',
    category: 'Java',
    subcategory: 'Concurrency & Parallelism',
    icon: Bolt,
    tags: ['CompletableFuture', 'Parallel Streams', 'Async'],
  },
  {
    id: 'java8-features',
    title: 'Java 8 — All Features',
    description: 'Lambdas, Streams, Optional, Functional Interfaces, Method References — with executable examples',
    category: 'Java',
    subcategory: 'Modern Java',
    icon: Code,
    tags: ['Lambda', 'Streams', 'Optional', 'Functional Interface'],
  },
  {
    id: 'java17-features',
    title: 'Java 17 — All Features',
    description: 'Records, Sealed Classes, Pattern Matching, Text Blocks — with executable examples',
    category: 'Java',
    subcategory: 'Modern Java',
    icon: Code,
    tags: ['Records', 'Sealed Classes', 'Pattern Matching', 'Text Blocks'],
  },
  {
    id: 'java-memory-model',
    title: 'Java Memory Model',
    description: 'Heap, stack, GC, memory leaks — understand where your objects live and die',
    category: 'Java',
    subcategory: 'JVM Internals',
    icon: Memory,
    tags: ['JVM', 'Heap', 'Stack', 'GC', 'Memory Leaks'],
  },
  {
    id: 'reactive-programming',
    title: 'Reactive Programming',
    description: 'Project Reactor, WebFlux, backpressure, R2DBC — when reactive makes sense and when it doesn\'t',
    category: 'Java',
    subcategory: 'Reactive Programming',
    icon: Waves,
    tags: ['Reactor', 'WebFlux', 'Mono', 'Flux', 'Backpressure', 'R2DBC'],
  },
  {
    id: 'java-coding-standards',
    title: 'Java Coding Standards',
    description: 'Team lead / architect guide — naming, structure, Git workflow, PR reviews, SOLID, testing, anti-patterns',
    category: 'Java',
    subcategory: 'Coding Standards & Best Practices',
    icon: Gavel,
    tags: ['Coding Standards', 'Git', 'PR Review', 'SOLID', 'Clean Code', 'Team Lead'],
  },
  // ── Spring Boot ──
  {
    id: 'spring-boot-fundamentals',
    title: 'Spring Boot Fundamentals',
    description: '@SpringBootApplication, auto-configuration, profiles, Actuator — how Spring Boot bootstraps itself',
    category: 'Spring Boot',
    subcategory: 'Fundamentals',
    icon: Layers,
    tags: ['Spring Boot', 'Auto-Config', 'Profiles', 'Actuator', '@SpringBootApplication'],
  },
  {
    id: 'spring-beans-di',
    title: 'Beans & Dependency Injection',
    description: 'Bean scopes, constructor vs field injection, @Qualifier, circular deps, bean lifecycle',
    category: 'Spring Boot',
    subcategory: 'Fundamentals',
    icon: Layers,
    tags: ['Beans', 'DI', 'Scopes', '@Autowired', '@Qualifier', 'Lifecycle'],
  },
  {
    id: 'spring-transactional',
    title: '@Transactional — Propagation & Isolation',
    description: 'Propagation types, isolation levels, self-invocation trap, rollback rules, readOnly pitfalls',
    category: 'Spring Boot',
    subcategory: 'Data & Transactions',
    icon: Layers,
    tags: ['@Transactional', 'Propagation', 'Isolation', 'Rollback', 'AOP Proxy'],
  },
  // ── SQL ──
  {
    id: 'sql-basics',
    title: 'SQL Basics — SELECT, WHERE, ORDER BY',
    description: 'Core SQL syntax — SELECT, filtering with WHERE, sorting, LIMIT, aliasing',
    category: 'SQL',
    subcategory: 'Fundamentals',
    icon: TableChart,
    tags: ['SQL', 'SELECT', 'WHERE', 'ORDER BY', 'LIMIT'],
  },
  {
    id: 'sql-joins',
    title: 'SQL Joins — INNER, LEFT, RIGHT, FULL',
    description: 'All join types with visual diagrams, self-join, when to use which',
    category: 'SQL',
    subcategory: 'Fundamentals',
    icon: TableChart,
    tags: ['SQL', 'INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'Self-Join'],
  },
  {
    id: 'sql-aggregates',
    title: 'Aggregates — GROUP BY, HAVING',
    description: 'COUNT, SUM, AVG, MIN, MAX — grouping rows, filtering groups, NULL handling',
    category: 'SQL',
    subcategory: 'Fundamentals',
    icon: TableChart,
    tags: ['SQL', 'GROUP BY', 'HAVING', 'COUNT', 'SUM', 'AVG'],
  },
  {
    id: 'sql-subqueries-cte',
    title: 'Subqueries & CTEs',
    description: 'Correlated subqueries, EXISTS, WITH clause, recursive CTEs for hierarchical data',
    category: 'SQL',
    subcategory: 'Advanced Queries',
    icon: TableChart,
    tags: ['SQL', 'Subquery', 'CTE', 'WITH', 'EXISTS', 'Recursive'],
  },
  {
    id: 'sql-window-functions',
    title: 'Window Functions — ROW_NUMBER, RANK, LAG',
    description: 'OVER(), PARTITION BY, ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD — the functions that differentiate senior devs',
    category: 'SQL',
    subcategory: 'Advanced Queries',
    icon: TableChart,
    tags: ['SQL', 'Window Functions', 'ROW_NUMBER', 'RANK', 'LAG', 'LEAD', 'PARTITION BY'],
  },
  {
    id: 'sql-indexing',
    title: 'Indexing & Query Optimization',
    description: 'B-tree internals, clustered vs non-clustered, composite index column order, EXPLAIN output',
    category: 'SQL',
    subcategory: 'Performance',
    icon: TableChart,
    tags: ['SQL', 'Index', 'B-Tree', 'EXPLAIN', 'Query Optimization', 'Composite Index'],
  },
  // ── DSA ──
  {
    id: 'dsa-two-pointers',
    title: 'Two Pointers Pattern',
    description: 'Same-direction and opposite-direction pointers — pair sum, 3Sum, Container With Most Water',
    category: 'DSA',
    subcategory: 'Patterns',
    icon: Psychology,
    tags: ['DSA', 'Two Pointers', 'Arrays', 'O(n)', 'Interview Pattern'],
  },
  {
    id: 'dsa-sliding-window',
    title: 'Sliding Window Pattern',
    description: 'Fixed and variable window — max sum subarray, longest substring, character frequency',
    category: 'DSA',
    subcategory: 'Patterns',
    icon: Psychology,
    tags: ['DSA', 'Sliding Window', 'Subarray', 'Substring', 'HashMap'],
  },
  {
    id: 'dsa-strings',
    title: 'String Problems',
    description: 'Anagram detection, palindrome, reverse words, compression — common interview string patterns',
    category: 'DSA',
    subcategory: 'Patterns',
    icon: Psychology,
    tags: ['DSA', 'Strings', 'Anagram', 'Palindrome', 'Frequency Map'],
  },
  {
    id: 'dsa-recursion',
    title: 'Recursion & Backtracking',
    description: 'Recursion mental model, base cases, backtracking template — subsets, permutations, N-Queens',
    category: 'DSA',
    subcategory: 'Patterns',
    icon: Psychology,
    tags: ['DSA', 'Recursion', 'Backtracking', 'Subsets', 'Permutations'],
  },
  {
    id: 'dsa-bfs-dfs',
    title: 'BFS & DFS — Trees and Graphs',
    description: 'Level-order BFS, recursive DFS, graph traversal, connected components, cycle detection',
    category: 'DSA',
    subcategory: 'Patterns',
    icon: Psychology,
    tags: ['DSA', 'BFS', 'DFS', 'Trees', 'Graphs', 'Level Order'],
  },
  // ── Docker ──
  {
    id: 'docker-fundamentals',
    title: 'Docker Fundamentals',
    description: 'Container vs VM, Dockerfile, images, volumes, networking — from zero to running containers',
    category: 'Docker',
    subcategory: 'Fundamentals',
    icon: ViewInAr,
    tags: ['Docker', 'Container', 'Dockerfile', 'Image', 'Volume', 'Networking'],
  },
  {
    id: 'docker-spring-boot',
    title: 'Dockerizing a Spring Boot App',
    description: 'Multi-stage Dockerfile, layered jars, environment config, health checks, .dockerignore',
    category: 'Docker',
    subcategory: 'Hands-On',
    icon: ViewInAr,
    tags: ['Docker', 'Spring Boot', 'Multi-Stage', 'Layered Jar', 'Health Check'],
  },
  {
    id: 'docker-compose',
    title: 'Docker Compose — Multi-Container Apps',
    description: 'Spring Boot + PostgreSQL + Redis in one compose file, depends_on, volumes, override files',
    category: 'Docker',
    subcategory: 'Hands-On',
    icon: ViewInAr,
    tags: ['Docker Compose', 'Multi-Container', 'PostgreSQL', 'Redis', 'Spring Boot'],
  },
  // ── Kubernetes ──
  {
    id: 'k8s-fundamentals',
    title: 'Kubernetes Fundamentals',
    description: 'Why Kubernetes exists, control plane vs nodes, Pods, the reconciliation loop, kubectl, and a local cluster with kind',
    category: 'Kubernetes',
    subcategory: 'Fundamentals',
    icon: Anchor,
    tags: ['Kubernetes', 'Pods', 'Control Plane', 'kubectl', 'kind', 'Declarative'],
  },
  {
    id: 'k8s-workloads',
    title: 'Workloads — Deployments, StatefulSets, Jobs',
    description: 'ReplicaSets, rolling updates and rollbacks, StatefulSets, DaemonSets, Jobs and CronJobs — choosing the right controller',
    category: 'Kubernetes',
    subcategory: 'Fundamentals',
    icon: Layers,
    tags: ['Deployment', 'ReplicaSet', 'StatefulSet', 'DaemonSet', 'Job', 'CronJob', 'Rolling Update'],
  },
  {
    id: 'k8s-networking',
    title: 'Networking — Services, Ingress, DNS',
    description: 'ClusterIP, NodePort, LoadBalancer, CoreDNS, Ingress and Gateway API, NetworkPolicies — how traffic reaches your pod',
    category: 'Kubernetes',
    subcategory: 'Networking & Config',
    icon: Lan,
    tags: ['Service', 'Ingress', 'Gateway API', 'DNS', 'NetworkPolicy', 'kube-proxy'],
  },
  {
    id: 'k8s-config-storage',
    title: 'Config, Secrets & Storage',
    description: 'ConfigMaps, Secrets (and why they are not secret), volumes, PV/PVC/StorageClass, external secret managers',
    category: 'Kubernetes',
    subcategory: 'Networking & Config',
    icon: Storage,
    tags: ['ConfigMap', 'Secret', 'PersistentVolume', 'PVC', 'StorageClass', 'External Secrets'],
  },
  {
    id: 'k8s-spring-boot',
    title: 'Deploying Spring Boot on Kubernetes',
    description: 'Probes, resources, graceful shutdown, config, HPA, and packaging with Helm — a production-ready Spring Boot deployment',
    category: 'Kubernetes',
    subcategory: 'Hands-On',
    icon: RocketLaunch,
    tags: ['Spring Boot', 'Probes', 'Helm', 'HPA', 'Graceful Shutdown', 'Resources'],
  },
  {
    id: 'k8s-production',
    title: 'Kubernetes in Production',
    description: 'Requests/limits and QoS, autoscaling, RBAC and pod security, observability, GitOps, and troubleshooting CrashLoopBackOff/OOMKilled',
    category: 'Kubernetes',
    subcategory: 'Production',
    icon: Shield,
    tags: ['Autoscaling', 'RBAC', 'QoS', 'GitOps', 'Argo CD', 'Troubleshooting', 'EKS'],
  },

  // ── AWS (developer's view; every service mapped to where ShopNorth uses it) ──
  {
    id: 'aws-start-here',
    title: 'AWS for Developers — Start Here',
    description: "Regions, accounts, the console, CLI and SDK, costs — and the map of every AWS service ShopNorth uses, why, and where to learn it",
    category: 'AWS',
    subcategory: 'Start Here',
    icon: Cloud,
    tags: ['AWS', 'Regions', 'Console', 'CLI', 'SDK', 'Well-Architected'],
  },
  {
    id: 'aws-iam',
    title: 'IAM, Secrets & Encryption',
    description: 'Policies and how AWS evaluates them, roles for pods, Lambda, and CI (OIDC), Identity Center, SCPs, Secrets Manager, and KMS',
    category: 'AWS',
    subcategory: 'Security & Networking',
    icon: VpnKey,
    tags: ['IAM', 'Roles', 'OIDC', 'Secrets Manager', 'KMS', 'Least Privilege'],
  },
  {
    id: 'aws-networking-vpc',
    title: 'Networking — VPC, Subnets & Security Groups',
    description: 'CIDR planning, public vs private subnets, NAT gateways, VPC endpoints, security groups vs NACLs, Route 53, and debugging connectivity',
    category: 'AWS',
    subcategory: 'Security & Networking',
    icon: Router,
    tags: ['VPC', 'Subnets', 'Security Groups', 'NAT Gateway', 'Route 53', 'VPC Endpoints'],
  },
  {
    id: 'aws-ec2-autoscaling',
    title: 'EC2, Load Balancers & Auto Scaling',
    description: 'Instance types and pricing, ALB vs NLB, target groups and health checks, Auto Scaling groups and policies, Karpenter, and quotas before a sale',
    category: 'AWS',
    subcategory: 'Compute',
    icon: Computer,
    tags: ['EC2', 'Auto Scaling', 'ALB', 'Spot', 'Savings Plans', 'Karpenter'],
  },
  {
    id: 'aws-lambda',
    title: 'Lambda & Serverless',
    description: 'Invocation models, cold starts and SnapStart for Java, concurrency, SQS batches, API Gateway, Step Functions — and ShopNorth’s three functions',
    category: 'AWS',
    subcategory: 'Compute',
    icon: Functions,
    tags: ['Lambda', 'Serverless', 'SnapStart', 'API Gateway', 'Step Functions'],
  },
  {
    id: 'aws-containers',
    title: 'Containers — ECR, ECS & EKS',
    description: 'A private registry done right, ECS task definitions and roles, what EKS manages and what you still own, Fargate, and choosing ECS or EKS',
    category: 'AWS',
    subcategory: 'Compute',
    icon: ViewInAr,
    tags: ['ECR', 'ECS', 'EKS', 'Fargate', 'Containers'],
  },
  {
    id: 'aws-sqs-sns',
    title: 'SQS & SNS — Queues and Fan-Out',
    description: 'Visibility timeouts, DLQs, Standard vs FIFO, idempotent consumers, SNS fan-out with filters — and ShopNorth’s email and SMS pipeline',
    category: 'AWS',
    subcategory: 'Messaging & Events',
    icon: Inbox,
    tags: ['SQS', 'SNS', 'DLQ', 'FIFO', 'Fan-out', 'Messaging'],
  },
  {
    id: 'aws-eventbridge',
    title: 'EventBridge — Routing Events by Content',
    description: 'Event buses, patterns, AWS and SaaS events, Scheduler, Pipes, archive and replay — and when to use SQS, SNS, EventBridge, or Kafka',
    category: 'AWS',
    subcategory: 'Messaging & Events',
    icon: CallSplit,
    tags: ['EventBridge', 'Event-Driven', 'Scheduler', 'Pipes', 'Serverless'],
  },
  {
    id: 'aws-msk',
    title: 'MSK — Managed Kafka',
    description: 'What MSK manages, provisioned vs serverless, IAM auth from Spring Boot, partitions as capacity, metrics to alarm on, and MSK Connect',
    category: 'AWS',
    subcategory: 'Messaging & Events',
    icon: Stream,
    tags: ['MSK', 'Kafka', 'Streaming', 'IAM Auth', 'Consumer Lag'],
  },
  {
    id: 'aws-s3',
    title: 'S3 — Object Storage',
    description: 'Secure defaults, bucket policies, presigned URLs for direct uploads, storage classes and lifecycle, versioning, Object Lock, and replication',
    category: 'AWS',
    subcategory: 'Storage & Databases',
    icon: Inventory2,
    tags: ['S3', 'Presigned URLs', 'Lifecycle', 'Storage Classes', 'Object Lock'],
  },
  {
    id: 'aws-databases',
    title: 'Databases — RDS, Aurora, DynamoDB & ElastiCache',
    description: 'RDS PostgreSQL as ShopNorth runs it, when to move to Aurora, DynamoDB key design, ElastiCache eviction traps, and safe upgrades',
    category: 'AWS',
    subcategory: 'Storage & Databases',
    icon: Storage,
    tags: ['RDS', 'Aurora', 'DynamoDB', 'ElastiCache', 'Multi-AZ', 'Read Replicas'],
  },
  {
    id: 'aws-cloudfront',
    title: 'CloudFront, Route 53, ACM & WAF — The Edge',
    description: 'Behaviors and cache keys, versioned assets vs invalidations, SPA routing, Origin Access Control, certificates, WAF rate limits, and sale night at the edge',
    category: 'AWS',
    subcategory: 'Edge',
    icon: Public,
    tags: ['CloudFront', 'CDN', 'WAF', 'Route 53', 'ACM', 'Caching'],
  },
  {
    id: 'aws-cloudformation',
    title: 'CloudFormation, SAM & CDK',
    description: 'Templates, change sets and replacements, protecting stateful resources, SAM for Lambda, CDK, Terraform vs CloudFormation, and IaC in CI/CD',
    category: 'AWS',
    subcategory: 'Operations',
    icon: IntegrationInstructions,
    tags: ['CloudFormation', 'SAM', 'CDK', 'Infrastructure as Code', 'Terraform'],
  },
  {
    id: 'aws-cloudwatch',
    title: 'CloudWatch & CloudTrail',
    description: 'Metrics and percentiles, EMF, Logs Insights, alarms that do not cry wolf, CloudWatch next to Datadog, CloudTrail audits, and cost control',
    category: 'AWS',
    subcategory: 'Operations',
    icon: Insights,
    tags: ['CloudWatch', 'CloudTrail', 'Alarms', 'Logs Insights', 'Observability'],
  },
];

export const getCategories = () => [...new Set(tutorialRegistry.map((t) => t.category))];

export const getSubcategories = (category) =>
  [...new Set(tutorialRegistry.filter((t) => t.category === category).map((t) => t.subcategory))];

export const getTutorialsByCategory = (category) =>
  tutorialRegistry.filter((t) => t.category === category);

export const getTutorialsBySubcategory = (category, subcategory) =>
  tutorialRegistry.filter((t) => t.category === category && t.subcategory === subcategory);

export const getTutorialById = (id) => tutorialRegistry.find((t) => t.id === id);

export const getCategoryIcon = (category) => {
  const map = {
    'ShopNorth Journey': Storefront,
    'System Design': Architecture,
    'Low-Level Design': Extension,
    'Real-World Builds': CloudUpload,
    'Architecture Decisions': CompareArrows,
    'Microservices': Hub,
    'Java': Code,
    'Spring Boot': EnergySavingsLeaf,
    'SQL': TableChart,
    'DSA': Psychology,
    'Docker': ViewInAr,
    'Kubernetes': Anchor,
    'AWS': Cloud,
    'AI Engineering': SmartToy,
  };
  return map[category] || Category;
};

export const getAdjacentTutorials = (id) => {
  const idx = tutorialRegistry.findIndex((t) => t.id === id);
  return {
    prev: idx > 0 ? tutorialRegistry[idx - 1] : null,
    next: idx < tutorialRegistry.length - 1 ? tutorialRegistry[idx + 1] : null,
  };
};

export default tutorialRegistry;
